language: python
python:
    - 3.6
    
jobs:
  dist:
     - focal
     - bionic

stages:
  - name: publish
    # Don't run build stage for pull requests and other branches than master
    # to save time and resources.
    if: type != pull_request AND (branch = master OR tag IS present)

services:
  - docker
  
before_install:
  - sudo apt-get -y install jq

install:
  - docker build -t cgwire/cgwire .
  - docker run -d -p 80:80 --name cgwire cgwire/cgwire


deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
    branch: master


script:
  - docker ps | grep -q cgwire
  - pip3 install httpie
  - http localhost:80/api | grep Zou
  - http localhost:80 | grep Kitsu
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword | jq .login 
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword | jq .login | grep true
